/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_uquark_mcmagic_voice_recognize_ps4j_PS4J */

#ifndef _Included_me_uquark_mcmagic_voice_recognize_ps4j_PS4J
#define _Included_me_uquark_mcmagic_voice_recognize_ps4j_PS4J
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_uquark_mcmagic_voice_recognize_ps4j_PS4J
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_uquark_mcmagic_voice_recognize_ps4j_PS4J_init
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     me_uquark_mcmagic_voice_recognize_ps4j_PS4J
 * Method:    startUtterance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_uquark_mcmagic_voice_recognize_ps4j_PS4J_startUtterance
  (JNIEnv *, jclass);

/*
 * Class:     me_uquark_mcmagic_voice_recognize_ps4j_PS4J
 * Method:    endUtterance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_uquark_mcmagic_voice_recognize_ps4j_PS4J_endUtterance
  (JNIEnv *, jclass);

/*
 * Class:     me_uquark_mcmagic_voice_recognize_ps4j_PS4J
 * Method:    addWord
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_me_uquark_mcmagic_voice_recognize_ps4j_PS4J_addWord
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     me_uquark_mcmagic_voice_recognize_ps4j_PS4J
 * Method:    process
 * Signature: ([BJZ)I
 */
JNIEXPORT jint JNICALL Java_me_uquark_mcmagic_voice_recognize_ps4j_PS4J_process
  (JNIEnv *, jclass, jbyteArray, jlong, jboolean);

/*
 * Class:     me_uquark_mcmagic_voice_recognize_ps4j_PS4J
 * Method:    getInSpeech
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_me_uquark_mcmagic_voice_recognize_ps4j_PS4J_getInSpeech
  (JNIEnv *, jclass);

/*
 * Class:     me_uquark_mcmagic_voice_recognize_ps4j_PS4J
 * Method:    getHypothesis
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_uquark_mcmagic_voice_recognize_ps4j_PS4J_getHypothesis
  (JNIEnv *, jclass);

/*
 * Class:     me_uquark_mcmagic_voice_recognize_ps4j_PS4J
 * Method:    getScore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_uquark_mcmagic_voice_recognize_ps4j_PS4J_getScore
  (JNIEnv *, jclass);

/*
 * Class:     me_uquark_mcmagic_voice_recognize_ps4j_PS4J
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_uquark_mcmagic_voice_recognize_ps4j_PS4J_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
